// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"roflbeacon2/app/api"
)

type Account struct {
	ID     int64
	Token  string
	Name   string
	ChatID *int64
	Status api.AccountStatus
}

type Fence struct {
	ID        int64
	Name      string
	Longitude float64
	Latitude  float64
	Radius    float64
}

type Migration struct {
	ID      string
	Applied time.Time
}

type Update struct {
	ID        int64
	AccountID int64
	Created   time.Time
	Data      api.UpdateData
}
